name: FortifePrefixes
version: dev
api: 3.0.0
main: FortifiePE\Prefixes\Main
authors:
  - Taskov1ch
  - FortifiePE
website: taskovich.pro
load: POSTWORLD

permissions:
  prefixes.*:
    children:
      prefixes.default:
        default: op
      prefixes.admin:
        default: op
      prefixes.ready_prefixes:
        default: op