name: FortifePrefixes
version: dev
api: 3.0.0
main: FortifePE\Prefixes\Main
author: Taskov1ch
website: taskovich.pro
load: POSTWORLD

permissions:
  prefifex.*:
    children:
      prefifex.default:
        default: op
      prefifex.admin:
        default: op
      prefifex.ready.prefixes:
        default: op