# Частота обновления префикса (в тиках, 0 для отключения)
update: 20

# Лимит длины префикса (включая символы цветов, не действует для администраторов)
limit: 20

# Частота сохранения данных в БД (в минутах)
save: 1

# Настройки базы данный (если не шарите, то лучше не трогайте)
database:
  provider: sqlite
  sqlite:
    path: database.db
  mysql:
    host: localhost:3306
    username: root
    password: qwerty
    scheme: prefixes
