# Регулярное обновление префикса в тиках (0 для выключения)
update: 0

# Лимит на длину префикса (считая цвета тоже, не действует на админов)
limit: 20

# Частота сохранения данных в БД (в минутах)
save: 1