# Частота обновления префикса в тиках (0 — для выключения)
update: 0

# Лимит длины префикса (включая символы цветов, не действует для администраторов)
limit: 20

# Частота сохранения данных в БД (в минутах)
save: 1
